### ISSUE TITLE
JS : Activerecord_sortable is not a function

### ISSUE THREAD

**Issue by DemisBand** [aishek/activerecord-sortable#12]
Hello,

I just installed the Gem and I have a problem:

I have made the statement javascript, and sortable.js file is loaded.
But Google Chrome gives me this error:

`Uncaught TypeError: $ (...) activerecord_sortable is not a function.
`

Can you help me ?
Thank you

**Comment by aishek** [comment]
Hi, could you provide a link to your code or to the app? JQuery is loaded?

**Comment by DemisBand** [comment]
Sorry I found the problem, the gem jquery ui was not loaded ... disturbing.

Thank you

**Comment by aishek** [comment]
Oh that's ok. Readme contains the example.

Glad, that you got it working
