### ISSUE TITLE
Limit order by category

### ISSUE THREAD

**Issue by Svashta** [aishek/activerecord-sortable#13]
Hi,

I have successfully implemented this gem, but would like to "limit" ordering to records in same category.
So, let's say i have Fish that belongs to FishCategory and i want to order fishes in same category, not globally. Is it just safe to leave it alone or is it a good idea to limit it by category - and if yes, how?

**Comment by aishek** [comment]
Sorry for realy sloooow answer.

So I think you should use limit with `config[:relation]` like so:

```ruby
class Fish < ActiveRecord::Base
  acts_as_sortable do |config|
    config[:relation] = ->(instance) { instance.class.where(category: 'sharks') }
  end
end
```
