### ISSUE TITLE
No handle for nil or oblong/strange numbers

### ISSUE THREAD

**Issue by Rockster160** [aishek/activerecord-sortable#4]
Working on getting this gem installed and running into a few errors. 

Specifically- setting `config[:append] = true` is causing: 
![screen shot 2015-06-29 at 11 50 32 am](https://cloud.githubusercontent.com/assets/8505362/8414567/2e255164-1e56-11e5-9a2d-be6e642ceb9a.png)

Also, this is pure recommendation from me-
Shouldn't you also have a descending scope if you have an ascending specified one??
Lack of nil handling is painful if you are hoping to have people using this that came from others. We used to use acts_as_list and want to move to this one, but have had to do a lot of changes to work around bugs like that. 
A possible fix for that, and also a very useful feature would be a 'refresh positions' method. Something that can be called manually (Or even just called before or after every update) that iterates through all of the positions and 'fixes' them. So any oblong position numbers (like 0, or even 10346 in an array that is only 5 or 6 long) would be fixed.

**Comment by Rockster160** [comment]
Sorry. Was a typo on my part- 
Still wish there was nil handling and handling for oblong numbers in general. I may submit a PR if I can get this project done soon.

**Comment by aishek** [comment]
@Rockster160 glad all works now )
