### ISSUE TITLE
Grid layout doesn't work correctly

### ISSUE THREAD

**Issue by tsbarnes** [aishek/activerecord-sortable#6]
I'm trying to use the jQuery UI Sortable [grid view](https://jqueryui.com/sortable/#display-grid) with activerecord-sortable, and it halfway works, but the look is messed up (dragged items only move up and down visually, though they end up in the right place once I drop them).

**Comment by aishek** [comment]
@tsbarnes if you could provide some source code I'll be able to help

**Comment by tsbarnes** [comment]
The index view uses this:

```haml
.row.widget-container{ data: { role: 'activerecord_sortable' } }
  = render @dashboard.widgets
```

The items are rendered using this partial:

```haml
.col-sm-12.col-md-6.col-lg-4.ui-state-default.widget{ data: { role: "widget#{dashboard_widget.id}", move: { url: "#{url_for([:move, :designer, dashboard_widget])}" }, position: "#{dashboard_widget.position}" } }
  = render dashboard_widget.widget
```

And the javascript returned on move:

```javascript
var node = $('*[data-role="widget<%= @dashboard_widget.id %>"]');
var new_node_html = '<%= j render @dashboard_widget %>';

node.replaceWith(new_node_html);
```

Moving items works, and will save the positions correctly, but while dragging the block it only follows the cursor vertically, horizontally it just stays at the far left side of the container until I drop it.  Using plain jQuery UI Sortable it follows the cursor both horizontally and vertically, just like in the example I linked to before.

**Comment by aishek** [comment]
It may be jQuery UI issue or something wrong with CSS. Provide HTML and CSS code?

**Comment by Rockster160** [comment]
This comes down to a hardcoded variable in the gem.
https://github.com/aishek/activerecord-sortable/blob/master/lib/assets/javascripts/sortable.js#L98
The axis is set to move only to 'y'.

**Comment by aishek** [comment]
@Rockster160 thanks for digging, I forgot it. If you'll create pull request for replace constant with option, I'll merge it.

**Comment by aishek** [comment]
I've added #7

**Comment by aishek** [comment]
@Rockster160 just created 0.0.6 release, which have `axis` option. Sorry for long time it took
