### ISSUE TITLE
The problem with sorting after removing entities.

### ISSUE THREAD

**Issue by seliverstov-maxim** [aishek/activerecord-sortable#8]
If I remove any entity then sorting work wrong. It seems that the positions must be updated after each destroying.

**Comment by aishek** [comment]
How you destroy entities?

**Comment by marktellez** [comment]
this is still a problem. whenever a sortable is deleted (destroy) then there is a gap in the position numbering, ie

[[26, "A", 0], [28, "B", 1], [29, "C", 2], [25, "D", 3], [27, "E", 4]]

Destroy D and you get

[[26, "A", 0], [28, "B", 1], [29, "C", 2], [27, "E", 4]]

Try to drag C to after E and in the UI it works fine, reload, and C will be under E still

[[26, "A", 0], [28, "B", 1], [29, "C", 3],  [27, "E", 4]]
